const express = require("express");
const router = express.Router();
const { signup } = require("../controllers/userController/userSignup");
const { login } = require("../controllers/userController/userLogin");
const { me } = require("../controllers/userController/userMe");
const { authenticateJwt } = require("../middlewares/authMiddleware");
const { SearchBook } = require("../controllers/BooksController/SearchBook");
router.post("/signup", signup);
router.post("/login", login);
router.get("/me", authenticateJwt, me);
router.get("/search", SearchBook);
module.exports = router;
